export const MOVIE_TYPES = {

  // getter
  MOVIES: 'MOVIES/MOVIES',
  MOVIE: 'MOVIES/MOVIE',

  // mutation
  INIT_MOVIES: 'MOVIES/INIT_MOVIES',
  CREATE_MOVIE: 'MOVIES/CREATE_MOVIE',
  UPDATE_MOVIE: 'MOVIES/UPDATE_MOVIE',
  DELETE_MOVIE: 'MOVIES/DELETE_MOVIE',
  SET_ACTIVE_MOVIE_INDEX: 'MOVIES/SET_ACTIVE_MOVIE_INDEX',
  UPDATE_LOCAL_STORAGE: 'MOVIES/UPDATE_LOCAL_STORAGE',
  UPDATE_STATE_FROM_STORAGE: 'MOVIES/UPDATE_STATE_FROM_STORAGE',
  ADD_ACTOR: 'MOVIES/ADD_ACTOR',
  ADD_ACTOR_RULE: 'MOVIES/ADD_ACTOR_RULE',
  // action 
  INIT_MOVIES_ACTION: 'MOVIES/INIT_MOVIES_ACTION',
  DELETE_MOVIE_ACTION: 'MOVIES/DELETE_MOVIE_ACTION',
  ADD_ACTOR_ACTION: 'MOVIES/ADD_ACTOR_ACTION',
  ADD_ACTOR_RULE_ACTION: 'MOVIES/ADD_ACTOR_RULE_ACTION',
  CREATE_MOVIE_ACTION: 'MOVIES/CREATE_MOVIE_ACTION',
  UPDATE_MOVIE_ACTION: 'MOVIES/UPDATE_MOVIE_ACTION',

}